name: VFM_DBT
version: 1.0.0
config-version: 2
profile: VFM_DBT
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
    staging:
      vfm_ncl_stg:
        +materialized: view
        +schema: L00_STG
      vfm_oci_stg:
        +materialized: view
        +schema: L00_STG
      vfm_rssc_stg:
        +materialized: view
        +schema: L00_STG
    RDV:
      vfm_ncl:
        +materialized: incremental
        +schema: L10_RDV
      vfm_oci:
        +materialized: incremental
        +schema: L10_RDV
      vfm_rssc:
        +materialized: incremental
        +schema: L10_RDV
        
