USE ROLE ACCOUNTADMIN;

-- Allow dbt Hub + GitHub codeload (minimum for dbt deps)
CREATE OR REPLACE NETWORK RULE DBT_DEPS_NETWORK_RULE
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = (
    'hub.getdbt.com',
    'codeload.github.com'
  );

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION DBT_DEPS_EXT_ACCESS
  ALLOWED_NETWORK_RULES = (DBT_DEPS_NETWORK_RULE)
  ENABLED = TRUE;
